galaxy_info:
  author: raphael
  description: Apply SELinux contexts and booleans for Nextcloud on AlmaLinux 9 (enforcing, targeted policy)
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags: []

dependencies: []
