---
- name: restart jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: restarted

- name: reload jenkins jobs
  ansible.builtin.uri:
    url: "http://localhost:{{ nas_jenkins_port }}/jenkins/reload"
    method: POST
    status_code: [200, 302]
  failed_when: false
