galaxy_info:
  author: raphael
  description: Configure nftables firewall rules (IPv4 + IPv6) via a single template on AlmaLinux 9
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags: []

dependencies: []
